
export enum FollowActionTypes {
    FETCH_FOLLOWERS_REQ = '@follow/FETCH_FOLLOWERS_REQ',
    FETCH_FOLLOWERS_SUC = '@follow/FETCH_FOLLOWERS_REQ',
    FETCH_FOLLOWING_REQ = '@follow/FETCH_FOLLOWING_REQ',
    FETCH_FOLLOWING_SUC = '@follow/FETCH_FOLLOWING_SUC',
    FOLLOW_REQ = '@follow/FOLLOW_REQ',
    FOLLOW_SUC = '@follow/FOLLOW_SUC',
    UNFOLLOW_REQ = '@follow/UNFOLLOW_REQ',
    UNFOLLOW_SUC = '@follow/UNFOLLOW_SUC',
}