export const USER_REGISTER_SUC = 'auth/USER_REGISTER_SUC'
export const USER_REGISTER_ERR = 'auth/USER_REGISTER_ERR'
export const USER_REGISTER_REQ = 'auth/USER_REGISTER_REQ'
export const USER_LOGIN_REQ = 'auth/USER_LOGIN_REQ'
export const USER_LOGIN_SUC = 'auth/USER_LOGIN_SUC'
export const USER_LOGIN_ERR = 'auth/USER_LOGIN_ERR'
