CREATE DATABASE GymNotebook3

USE [GymNotebook3]

CREATE TABLE [Users] (
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[Username] NVARCHAR(100) NULL,
	[Email] NVARCHAR(100) NOT NULL,
	[Role] NVARCHAR(10)  NULL,
	[Password] NVARCHAR(200) NOT NULL,
	[Salt] NVARCHAR(200) NOT NULL,
	[CreateAt] DATETIME NOT NULL)
SELECT * FROM [Users];

CREATE TABLE [dbo].[Images](
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[UserId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id) NOT NULL,
	[Content] IMAGE NOT NULL
) 
SELECT * FROM [Images]

CREATE TABLE [dbo].[Profiles](
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[UserId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id) NOT NULL,
	[FirstName] NVARCHAR(50) NOT NULL,
	[LastName] NVARCHAR(50) NOT NULL,
	[Gender] NVARCHAR(50) NOT NULL,
	[DateOfBirth] DATE NOT NULL,
	[Location] NVARCHAR(100) NULL,
	[Description] NVARCHAR(MAX) NULL,
	[ImageId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Images(Id) NULL,
	[IsTrainer] BIT NOT NULL,
	[TrainerType] NVARCHAR(50) NULL,
	[AverageRates] REAL NOT NULL,
	[FollowingCount] INT NOT NULL,
	[FollowersCount] INT NOT NULL,
	[AccountType] NVARCHAR(50) NULL,
	[AccountTypeExpiration] DATE NULL,
	[UpdatedAt] DATETIME NOT NULL
)
SELECT * FROM [Profiles];

CREATE TABLE [Trainings] (
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[UserId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id) NOT NULL,
	[Name] nvarchar(100) NOT NULL,
	[Description] nvarchar(100) NOT NULL,
	[Difficulty] NVARCHAR(100) NOT NULL)
SELECT * FROM [Trainings];

CREATE TABLE [Routines] (
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[TrainingId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Trainings(Id) NOT NULL,
	[Name] VARCHAR(100) NOT NULL)
SELECT * FROM [Routines];

CREATE TABLE [Exercises] (
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[RoutineId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Routines(Id) NOT NULL,
	[Name] VARCHAR(100) NOT NULL,
	[Description] VARCHAR(100) NOT NULL,
	[MusclePart] VARCHAR(100) NOT NULL)
SELECT * FROM [Exercises]

CREATE TABLE [Results] (
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[ExerciseId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Exercises(Id) NOT NULL,
	[NumberSeries] INT NOT NULL,
	[Repetitions] INT NOT NULL,
	[Weight] FLOAT NOT NULL,
	[Comments] NVARCHAR(250) NULL,
	[CreatedAt] DATETIME NOT NULL)
SELECT * FROM [Results]

CREATE TABLE [Progress] (
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[UserId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id) NOT NULL,
	[Weight] REAL NULL,
	[Biceps] REAL NULL,
	[Chest] REAL NULL,
	[Thigh] REAL NULL,
	[Calf] REAL NULL,
	[Waist] REAL NULL,
	[Shoulders] REAL NULL,
	[Neck] REAL NULL,
	[CreatedAt] DATETIME NOT NULL)
SELECT * FROM [Progress]

CREATE TABLE [Friends] (
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[UserId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id) NOT NULL,
	[FriendId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id) NOT NULL,
	[FriendStatus] INT NULL,
	[DateAdded] DATETIME NOT NULL)
SELECT * FROM [Friends]

CREATE TABLE [dbo].[Comments](
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[CommentNumber] INT NOT NULL,
	[CommentedUserId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id) NOT NULL,
	[CommentedById] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id) NOT NULL,
	[Comment] NVARCHAR(MAX) NOT NULL,
	[CommentedAt] DATETIME NOT NULL
) 
SELECT * FROM [Comments]

CREATE TABLE [dbo].[Follows](
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[Follower] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id) NOT NULL,
	[Followed] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id) NOT NULL,
	[CreatedAt] DATETIME NOT NULL
)
SELECT * FROM [Follows]

CREATE TABLE [dbo].[Rates](
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[RateUserId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id) NOT NULL,
	[RateByUserId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id) NOT NULL,
	[Rate] INT NOT NULL,
	[RatingDate] DATE NOT NULL
)
SELECT * FROM [Rates]

CREATE TABLE [dbo].[Posts](
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[UserId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id) NOT NULL,
	[Description] NVARCHAR(500) NOT NULL,
	[ImageId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Images(Id) NOT NULL,
	[Likes] INT NOT NULL,
	[CreatedAt] DATETIME NOT NULL
) ON [PRIMARY]
GO